title: What is Nuclear?
email: contact@whatisnuclear.com
description: >-
  A no-nonsense public education site on nuclear energy.
baseurl: "" 
url: "https://whatisnuclear.com" 
twitter_username: whatisnuclear
github_username: whatisnuclear
github_repo_url: https://github.com/whatisnuclear/website/blob/master/
title_image: https://whatisnuclear.com/img/reactor_200.png

markdown: kramdown
highlighter: rouge
collections:
  posts:
    output: true
    directory: blog
    permalink: /blog/:year-:month-:day-:title.html
  news:
    output: true
    directory: news
    permalink: /news/:year-:month-:day-:title.html

kramdown:
  toc_levels: "1,2,3"

plugins: 
  - jekyll-sitemap
  - jekyll-time-to-read
  - jekyll-feed

feed:
    collections:
        news: 
            # This is the main news section describing changes and additions to the site. 
            # This is what people would likely point their feed reader too
            path: "/feed.xml"
        posts: 
            # ATM these are kind of an "other" category rather than a blog
            path: "/blog.xml"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
